/**
 * Device Debug Agent — Android Unity 项目调试文档生成器
 *
 * 为 Unity Android 项目自动生成 DEBUGGING.md、ANDROID_SDK_INTEGRATION.md、
 * BUG_REPORT_TEMPLATE.md 三份开发辅助文档。
 *
 * 所有命令均使用公开 Android Debug Bridge (adb) 标准命令，不含私有工具或参数。
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { generateAndroidSdkDoc } from './android-sdk-planner.js';
import type { AndroidSdkIntegrationConfig } from './types.js';

export interface DebugDocGenerationResult {
  debuggingPath: string;
  androidSdkPath: string;
  bugReportTemplatePath: string;
}

/**
 * 为 Unity Android 项目生成全套调试文档。
 *
 * @param workspacePath 项目工作区根路径
 * @param config SDK 集成配置
 * @returns 生成的文件路径集合
 */
export function generateDebugDocs(
  workspacePath: string,
  config: Partial<AndroidSdkIntegrationConfig> = {},
): DebugDocGenerationResult {
  const docsDir = join(workspacePath, 'docs');
  mkdirSync(docsDir, { recursive: true });

  // 1. 调试指南
  const debuggingPath = join(docsDir, 'DEBUGGING.md');
  writeFileSync(debuggingPath, generateDebuggingDoc(config), 'utf-8');

  // 2. Android SDK 集成文档
  const androidSdkPath = generateAndroidSdkDoc(workspacePath, config);

  // 3. Bug 报告模板
  const bugReportTemplatePath = join(docsDir, 'BUG_REPORT_TEMPLATE.md');
  writeFileSync(bugReportTemplatePath, generateBugReportTemplate(config), 'utf-8');

  return { debuggingPath, androidSdkPath, bugReportTemplatePath };
}

/* ===================== 文档内容生成 ===================== */

function generateDebuggingDoc(config: Partial<AndroidSdkIntegrationConfig>): string {
  const pkg = config.packageName ?? 'com.example.unitygame';

  return [
    `# Android Unity Debugging Guide`,
    ``,
    `> 本文档覆盖 Unity Android 项目的本地真机调试流程。`,
    ``,
    `---`,
    ``,
    `## 1. 环境配置`,
    ``,
    `### 1.1 前置条件`,
    ``,
    `- [ ] Android SDK Platform-Tools 已安装（adb 可用）`,
    `- [ ] 设备已开启「开发者选项」和「USB 调试」`,
    `- [ ] USB 数据线连接正常，或无线调试已配对`,
    `- [ ] Unity Build Settings 中 \`Development Build\` + \`Script Debugging\` 已勾选`,
    ``,
    `### 1.2 验证连接`,
    ``,
    `\`\`\`bash`,
    `# 列出已连接设备`,
    `adb devices`,
    ``,
    `# 预期输出类似：`,
    `# List of devices attached`,
    `# XXXXXXXX    device`,
    `\`\`\``,
    ``,
    `---`,
    ``,
    `## 2. 安装 Android install package`,
    ``,
    `\`\`\`bash`,
    `# 安装（覆盖已有版本）`,
    `adb install -r path/to/your-game.android-package`,
    ``,
    `# 首次安装（不覆盖）`,
    `adb install path/to/your-game.android-package`,
    ``,
    `# 安装到 SD 卡`,
    `adb install -s path/to/your-game.android-package`,
    ``,
    `# 带降级权限安装（Android 5.0+）`,
    `adb install -d path/to/your-game.android-package`,
    `\`\`\``,
    ``,
    `---`,
    ``,
    `## 3. 启动应用`,
    ``,
    `\`\`\`bash`,
    `# 方式 1: 通过包名启动 `,
    `adb shell monkey -p ${pkg} -c android.intent.category.LAUNCHER 1`,
    ``,
    `# 方式 2: 通过 Activity Manager 启动（指定 Activity）`,
    `adb shell am start -n ${pkg}/com.unity3d.player.UnityPlayerActivity`,
    ``,
    `# 方式 3: 启动时传递 Intent extras`,
    `adb shell am start -n ${pkg}/com.unity3d.player.UnityPlayerActivity \\`,
    `  -e deepLink "myapp://open?scene=main"`,
    `\`\`\``,
    ``,
    `---`,
    ``,
    `## 4. 日志收集 (Logcat)`,
    ``,
    `### 4.1 实时日志`,
    ``,
    `\`\`\`bash`,
    `# 清除缓冲区后开始`,
    `adb logcat -c && adb logcat`,
    ``,
    `# 按优先级过滤（V/D/I/W/E/F）`,
    `adb logcat *:W`,
    ``,
    `# 按标签过滤（Unity + 常见 SDK 标签）`,
    `adb logcat -s Unity:V AdMob:V Firebase:V GooglePlay:V`,
    ``,
    `# 按包名过滤`,
    `adb logcat --pid=$(adb shell pidof ${pkg})`,
    ``,
    `# 导出到文件`,
    `adb logcat -d > logcat_full.txt`,
    `\`\`\``,
    ``,
    `### 4.2 崩溃日志`,
    ``,
    `\`\`\`bash`,
    `# 仅查看崩溃日志缓冲区`,
    `adb logcat -d -b crash`,
    ``,
    `# 搜索 FATAL 级别异常`,
    `adb logcat -d | grep "FATAL EXCEPTION"`,
    ``,
    `# 导出崩溃日志`,
    `adb logcat -d -b crash > crash_log.txt`,
    `\`\`\``,
    ``,
    `---`,
    ``,
    `## 5. 截图与录屏`,
    ``,
    `### 5.1 截图`,
    ``,
    `\`\`\`bash`,
    `# 截图并保存到电脑`,
    `adb exec-out screencap -p > screenshot.png`,
    ``,
    `# 截图并保存到设备`,
    `adb shell screencap /sdcard/screenshot.png`,
    `adb pull /sdcard/screenshot.png`,
    `\`\`\``,
    ``,
    `### 5.2 录屏`,
    ``,
    `\`\`\`bash`,
    `# 开始录屏（最大 180 秒）`,
    `adb shell screenrecord /sdcard/demo.mp4`,
    ``,
    `# Ctrl+C 停止录屏后拉取`,
    `adb pull /sdcard/demo.mp4`,
    `\`\`\``,
    ``,
    `---`,
    ``,
    `## 6. UI 自动化调试`,
    ``,
    `\`\`\`bash`,
    `# 导出当前 UI 层级`,
    `adb shell uiautomator dump`,
    `adb pull /sdcard/window_dump.xml`,
    ``,
    `# 模拟点击坐标`,
    `adb shell input tap 500 1000`,
    ``,
    `# 模拟滑动`,
    `adb shell input swipe 500 1500 500 500 300`,
    ``,
    `# 输入文本`,
    `adb shell input text "HelloUnity"`,
    `\`\`\``,
    ``,
    `---`,
    ``,
    `## 7. 性能监控`,
    ``,
    `\`\`\`bash`,
    `# CPU 使用率`,
    `adb shell top -b -n 1 | grep ${pkg}`,
    ``,
    `# 内存信息`,
    `adb shell dumpsys meminfo ${pkg}`,
    ``,
    `# GPU 渲染性能`,
    `adb shell dumpsys gfxinfo ${pkg}`,
    ``,
    `# 电池消耗`,
    `adb shell dumpsys batterystats ${pkg}`,
    `\`\`\``,
    ``,
    `---`,
    ``,
    `## 8. 完整 Bug Report`,
    ``,
    `\`\`\`bash`,
    `# 生成完整的 bug report 压缩包`,
    `adb bugreport`,
    `\`\`\``,
    ``,
    `---`,
    ``,
    `## 9. 无线调试 (Android 11+)`,
    ``,
    `\`\`\`bash`,
    `# 1. 设备上进入「开发者选项」→「无线调试」`,
    `# 2. 配对设备（使用配对码）`,
    `adb pair <ip>:<port> <pairing_code>`,
    ``,
    `# 3. 连接设备`,
    `adb connect <ip>:<port>`,
    ``,
    `# 验证`,
    `adb devices`,
    `\`\`\``,
    ``,
    `---`,
    ``,
    `## 10. 常见问题`,
    ``,
    `| 问题 | 排查步骤 |`,
    `|---|---|`,
    `| adb 无法识别设备 | 1. \`adb kill-server && adb start-server\` 2. 检查 USB 调试授权 3. 更换数据线/接口 |`,
    `| Android install package 安装失败 (INSTALL_FAILED_UPDATE_INCOMPATIBLE) | \`adb uninstall ${pkg}\` 后重新安装 |`,
    `| logcat 无 Unity 日志 | 确认 Build Settings 中 \`Development Build\` 已勾选 |`,
    `| screencap 返回黑屏 | 部分安全页面（如支付、银行类 Activity）禁止截图，切换回游戏场景重试 |`,
    `| 性能数据为空 | 部分设备需在「开发者选项」中开启「GPU 呈现模式分析」 |`,
    ``,
  ].join('\n');
}

function generateBugReportTemplate(config: Partial<AndroidSdkIntegrationConfig>): string {
  const pkg = config.packageName ?? 'com.example.unitygame';

  return [
    `# Bug Report Template`,
    ``,
    `> 提交 Bug 时，请尽量填写以下信息。信息越完整，修复越快。`,
    ``,
    `---`,
    ``,
    `## 基本信息`,
    ``,
    `- **Bug 标题**: [简短描述问题，如 "支付完成后未收到道具"]`,
    `- **严重程度**: [ ] 崩溃 / [ ] 功能异常 / [ ] 显示问题 / [ ] 性能问题`,
    `- **复现频率**: [ ] 必现 / [ ] 偶现 (约 N 次中 1 次) / [ ] 仅一次`,
    `- **发现版本**: [如 v1.2.3 build 456]`,
    `- **发现时间**: [YYYY-MM-DD HH:MM]`,
    ``,
    `---`,
    ``,
    `## 设备信息`,
    ``,
    `- **设备型号**: [如 Samsung Galaxy S23]`,
    `- **Android 版本**: [如 Android 14 (API 34)]`,
    `- **系统语言**: [如 简体中文]`,
    `- **网络环境**: [ ] Wi-Fi / [ ] 4G / [ ] 5G / [ ] 离线`,
    `- **存储空间**: [可用空间 / 总空间]`,
    `- **包名**: \`${pkg}\``,
    ``,
    `获取设备信息命令：`,
    `\`\`\`bash`,
    `adb shell getprop ro.product.model`,
    `adb shell getprop ro.build.version.release`,
    `adb shell getprop ro.build.version.sdk`,
    `adb shell getprop persist.sys.locale`,
    `\`\`\``,
    ``,
    `---`,
    ``,
    `## 复现步骤`,
    ``,
    `1. `,
    `2. `,
    `3. `,
    `... (越详细越好)`,
    ``,
    `---`,
    ``,
    `## 预期行为`,
    ``,
    `[描述正常情况下应该发生什么]`,
    ``,
    `---`,
    ``,
    `## 实际行为`,
    ``,
    `[描述实际发生了什么，包括错误提示、画面异常等]`,
    ``,
    `---`,
    ``,
    `## 附件`,
    ``,
    `请尽可能附上以下文件：`,
    ``,
    `- [ ] **截图/录屏**: 异常画面或操作过程`,
    `  \`\`\`bash`,
    `  adb exec-out screencap -p > screenshot.png`,
    `  \`\`\``,
    `- [ ] **Logcat 日志**:`,
    `  \`\`\`bash`,
    `  adb logcat -d > logcat.txt`,
    `  \`\`\``,
    `- [ ] **崩溃日志**: (如果发生崩溃)`,
    `  \`\`\`bash`,
    `  adb logcat -d -b crash > crash_log.txt`,
    `  \`\`\``,
    `- [ ] **Bug Report 压缩包**:`,
    `  \`\`\`bash`,
    `  adb bugreport bugreport.zip`,
    `  \`\`\``,
    `- [ ] **UI 层级文件**: (如果涉及 UI 问题)`,
    `  \`\`\`bash`,
    `  adb shell uiautomator dump && adb pull /sdcard/window_dump.xml`,
    `  \`\`\``,
    ``,
    `---`,
    ``,
    `## 补充说明`,
    ``,
    `[其他有助于定位问题的信息]`,
    ``,
  ].join('\n');
}
